### ISSUE TITLE
File names ordering

### ISSUE THREAD

**Issue by neo** [Jam3/jam3-lessons-react#11]
It would make more sense to name the sections numbered less than 10 `0*` in order for them to be ordered correctly on the file list. Also, we could correct the section number at the meantime.

**Comment by neo** [comment]
I could do it if you want. @jeremenichelli

**Comment by jeremenichelli** [comment]
@neolwc don't worry, I'm already on the way of fixing this, thank you

**Comment by neo** [comment]
wonderful
